# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: aab4733aa788979c422c8f28eb7a89fa5936cd36727a2dcb46bf73bef1594177b5fcd8647d99a4667b0c0134d063ce6ba60f45929246750bade00b827e81152c

test:
  secret_key_base: 596887a0e19b08081238bad7f9b1214c2cb70589002252eb2b8ea7b98ac1bb88e25e9ee22fb1f8e47be1a35b47d1f7fbfe26ed844bf0a87c0d3ea701bd6358d3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: 1704a5c84e769a17e0eba6f8d4cd16246bb63a4bda8a8668067043a780e3888fa5bb579b7006513c4feace28f336acfe760aa9572a82b86dabd4a6e5dec2b064
